language: go

before_install:
  - go get github.com/wadey/gocovmerge

script:
  - go list -f '{{if gt (len .TestGoFiles) 0}}" go test -covermode count -coverprofile {{.Name}}.coverprofile -coverpkg ./... {{.ImportPath}}"{{end}}' ./... | xargs -I {} bash -c {}
  - gocovmerge `ls *.coverprofile` > coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt
