// Code generated by "stringer -type=Op"; DO NOT EDIT

package vm

import "fmt"

const _Op_name = "OpNOPOpLOADOpLOOKUPOpLOOKUPCOpCONSOpCAROpCDROpSETCAROpSETCDROpTYPEOpAPPLYOpRETURNOpEVALOpDROPOpDUPOpSELECTOpJOINOpEQUALOpADDOpSUBOpMULOpDIVOpMODOpREADOpPRINTOpEND"

var _Op_index = [...]uint8{0, 5, 11, 19, 28, 34, 39, 44, 52, 60, 66, 73, 81, 87, 93, 98, 106, 112, 119, 124, 129, 134, 139, 144, 150, 157, 162}

func (i Op) String() string {
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return fmt.Sprintf("Op(%d)", i)
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
