// Code generated by "stringer -type=Op"; DO NOT EDIT

package vm

import "fmt"

const _Op_name = "OpNOPOpLOADOpLOOKUPOpLOOKUPCOpCONSOpCAROpCDROpSETCAROpSETCDROpTYPEOpAPPLYOpDAPPLYOpRETURNOpEVALOpDROPOpDUPOpSELECTOpJOINOpEQUALOpADDOpSUBOpMULOpDIVOpMODOpREADOpPRINTOpEND"

var _Op_index = [...]uint8{0, 5, 11, 19, 28, 34, 39, 44, 52, 60, 66, 73, 81, 89, 95, 101, 106, 114, 120, 127, 132, 137, 142, 147, 152, 158, 165, 170}

func (i Op) String() string {
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return fmt.Sprintf("Op(%d)", i)
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
